name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: |
        cd wa_web_clone
        npm install
    - name: Deploy to GH Pages
      run: |
        git config --global user.email andrenugroho395@gmail.com
        git config --global user.name andre-fajar-n
        git remote set-url origin https://${{secrets.GH_TOKEN}}@github.com/andre-fajar-n/WA-web-clone.git
        npm run deploy